#!/usr/bin/env sh
set -e
. "$(dirname -- "$0")/_/husky.sh"

cwd=$(pwd)
echo $cwd

echo "yarn pre-commit:"
cd $cwd/ && yarn pre-commit
 
echo "deno check types:"
cd $cwd/packages/api_bo/ && deno bundle src/app.ts -- .bundle 
rm -fr .bundle
cd $cwd/packages/api_m/ && deno bundle src/app.ts -- .bundle
rm -fr .bundle
